env:
  es6: true
  mocha: true
  amd: true
  node: true
  browser: true

ecmaFeatures:
  modules: false

globals:
  loot: false
  should: false

extends:
  - "eslint:recommended"
  - "airbnb/base"

rules:
  strict:
    - 2
    - global
  guard-for-in: 1
  no-param-reassign:
    - 2
    - props: false
  arrow-body-style: 1
  max-len: 1

plugins:
  - eslint-plugin-html
