env:
  es6: true
  mocha: true
  amd: true
  node: true
  browser: true

ecmaFeatures:
  modules: false

globals:
  loot: false
  should: false

extends:
  - "eslint:recommended"
  - "airbnb/base"

rules:
  strict:
    - 2
    - global
  no-param-reassign:
    - 2
    - props: false
  max-len: 1

plugins:
  - eslint-plugin-html
