parserOptions:
  ecmaVersion: 7
  sourceType: script

env:
  es6: true
  mocha: true
  amd: true
  node: true
  browser: true

globals:
  loot: false
  should: false

extends:
  - "eslint:recommended"
  - "airbnb-base"
  - "prettier"

rules:
  prettier/prettier: error
  no-param-reassign:
    - error
    - props: false
  no-underscore-dangle: off
  curly: [error, all]
  no-confusing-arrow: error

plugins:
  - html
  - prettier
