env:
  es6: true
  mocha: true
  amd: true
  node: true
  browser: true

globals:
  loot: false
  should: false

extends:
  - "eslint:recommended"
  - "airbnb-base"

rules:
  strict: off
  no-param-reassign:
    - error
    - props: false
  max-len: warn
  linebreak-style: off
  no-underscore-dangle: off
  arrow-parens: off
  no-undef: warn
  no-mixed-operators:
    - error
    - allowSamePrecedence: true

plugins:
  - eslint-plugin-html
