env:
  es6: true
  mocha: true
  amd: true
  node: true
  browser: true

ecmaFeatures:
  modules: false

globals:
  loot: false

extends:
  - "eslint:recommended"
  - "airbnb/base"

rules:
  strict:
    - 2
    - global
  no-new: 1
