sudo: false
language: cpp
compiler: gcc

# Need GCC 5 and Boost 1.54+, which aren't in the 12.04 repositories - install
# from PPAs. Also install the libssl-dev package, which is needed to build
# libgit2 with support for cloning from HTTPS URLs.
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost-log1.55-dev
      - libboost-date-time1.55-dev
      - libboost-thread1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-locale1.55-dev
      - libboost-iostreams1.55-dev
      - libssl-dev
      - gcc-5
      - g++-5

install:
  # Use GCC 5.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  # Run install step script to download and build dependencies.
  - chmod +x scripts/install-step.travis.sh
  - ./scripts/install-step.travis.sh

before_script:
  # Build Google Test
  - cd ../..
  - wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz -O - | tar -xz
  - cd googletest-release-1.7.0
  - cmake .
  - make
  # Move back into the cloned LOOT repo path.
  - cd $TRAVIS_BUILD_DIR/build
  # Fetch plugins to test with.
  - wget https://github.com/WrinklyNinja/testing-plugins/archive/1.0.0.tar.gz -O - | tar -xz
  - mv testing-plugins-1.0.0/* ./
  # Fetch metadata to test with.
  - wget https://github.com/loot/testing-metadata/archive/1.0.0.tar.gz -O - | tar -xz
  - mv testing-metadata-1.0.0 testing-metadata
  # Travis machines are 64 bit, and the dependencies use dynamic linking.
  - cmake .. -DPROJECT_ARCH=64 -DPROJECT_STATIC_RUNTIME=OFF -DBUILD_SHARED_LIBS=OFF -DGTEST_ROOT=../../googletest-release-1.7.0

script: make tests && ./tests

before_deploy:
  # Build the metadata validator
  - make metadata-validator
  - tar -pczf metadata-validator.tar.gz metadata-validator

deploy:
  provider: releases
  api_key:
    secure: NXzSdk+TrMSRRaCf0hpCv0LS5Ow+LJTsI5pymUThljk2w7QEQMws3lET82W4fnVLYTB3hde94g2tT2oclzQzdbg6l9E6uNwv6mznu8ovTzvOLwnOAvWXtA7aB6ovxu1WrkCkKfcBB0sk8Ezt7UejQu5o0G09z699coWeuUxLFJk=
  file: metadata-validator.tar.gz
  skip_cleanup: true
  on:
    repo: loot/loot
    tags: true

notifications:
  irc:
    channels:
      - "chat.freenode.net#loot"
    use_notice: true
    skip_join: true
