sudo: false
language: cpp
compiler: gcc

# Need GCC 5 and Boost 1.54+, which aren't in the 12.04 repositories - install
# from PPAs. Also install the libssl-dev package, which is needed to build
# libgit2 with support for cloning from HTTPS URLs.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # ppa:ubuntu-toolchain-r/test
      - kubuntu-backports       # ppa:kubuntu-ppa/backports
    packages:
      - libbz2-dev
      - libssl-dev
      - gcc-5
      - g++-5
      - cmake
      - cmake-data
  sauce_connect: true

cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/bower_components
    - $HOME/boost_1_61_0/boost
    - $HOME/boost_1_61_0/stage/lib

install:
  # Use GCC 5.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  # Install the latest stable Node.js. The default Node.js version is too old
  # for some of the JavaScript syntax used.
  - npm install -g nvm
  - nvm install node
  # Install Node.js dependencies
  - npm install
  # Add local binary path to PATH
  - export PATH="./node_modules/.bin:$PATH"
  # Install runtime dependencies using Bower
  - bower install
  - chmod +x scripts/travis/install_boost.sh
  - scripts/travis/install_boost.sh

before_script:
  # Move into the cloned LOOT repo build path.
  - mkdir build && cd build
  # Link dynamically to the C++ standard library runtime.
  - cmake .. -DPROJECT_STATIC_RUNTIME=OFF -DBOOST_ROOT=~/boost_1_61_0

script:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm test; fi
  - export CXXFLAGS="-fPIC" CFLAGS="-fPIC"
  - make tests && ./tests
  - make api-tests && ./api-tests

before_deploy:
  # Build the metadata validator
  - make metadata-validator
  - tar -pczf metadata-validator.tar.gz metadata-validator

deploy:
  provider: releases
  api_key:
    secure: NXzSdk+TrMSRRaCf0hpCv0LS5Ow+LJTsI5pymUThljk2w7QEQMws3lET82W4fnVLYTB3hde94g2tT2oclzQzdbg6l9E6uNwv6mznu8ovTzvOLwnOAvWXtA7aB6ovxu1WrkCkKfcBB0sk8Ezt7UejQu5o0G09z699coWeuUxLFJk=
  file: metadata-validator.tar.gz
  skip_cleanup: true
  on:
    repo: loot/loot
    tags: true

notifications:
  irc:
    channels:
      - "chat.freenode.net#loot"
    use_notice: true
    skip_join: true

env:
  global:
  - secure: OWgDkff/b+0eKk/P75rBnecaPDv1E/gMkCzsTUUtofmzj+sttpMUsh8VOVUvckGs5m3fRwRhc/t99gR4FuDtMOVE5JZ8CqZn7tcv2wNAspQ613pS0nWyIX/IUbyF+gjtPW2dWy81hKVtTP4yFvUn1Gk+JRjJLSyxM53Xt6oTOlY=
  - secure: XpGbqizjWfaGiWDkrcW4UhSW8ijm00jgSo2qkthza3QmHQ3C0Vye3gQjjITCq+y6izQTPa46fxaI+Ozligyh4aQ1G8SpCa77tXMBfvo31led+s81FlAOSVGDJ/2eDOoawFuj5dTKTPR1zLniDYH8AqG8EDZuLoK6fhx7CchU2Yw=
