# BOSS Settings File
# This file is written in YAML <http://www.yaml.org/>.

Language:            eng    # An ISO 639-3 language string.

Game:                auto   # auto, oblivion, nehrim, skyrim, fallout3, falloutnv
Last Game:           auto   # auto, oblivion, nehrim, skyrim, fallout3, falloutnv
Debug Verbosity:     0      # 0, 1, 2, 3. Logging takes place if > 0.
Update Masterlist:   true
View Report Externally: false

Masterlist URLs:
  Oblivion:          http://better-oblivion-sorting-software.googlecode.com/svn/data/boss-oblivion/masterlist.yaml
  Skyrim:            http://better-oblivion-sorting-software.googlecode.com/svn/data/boss-skyrim/masterlist.yaml
  Fallout 3:         http://better-oblivion-sorting-software.googlecode.com/svn/data/boss-fallout/masterlist.yaml
  Fallout New Vegas: http://better-oblivion-sorting-software.googlecode.com/svn/data/boss-fallout-nv/masterlist.yaml

Total Conversions:

  - name: Nehrim - At Fate's Edge
    base: oblivion
    master: Nehrim.esm
    folder: Nehrim
    
  - name: Enderal - The Shards of Order
    base: skyrim
    master: Enderal.esm
    folder: Enderal
