# Different color roles affect different elements:
#
# window
#   - background for toolbar, status bar, toolbox and non-native dialogs
# windowText
#   - icons
#   - text in settings window, dialogs, metadata editor plugin name, metadata
#     editor group input label, metadata editor tab labels
# base
#   - background for cards, multiline text inputs, the sidebar plugin list, the
#     sidebar filters panel and the settings panel list
# placeholderText
#   - placeholders
# text
#   - most text
#   - disabled menu bar text
# button
#   - toolbox buttons
# buttonText
#   - buttons
#   - table section headers
#   - enabled tab bar scroll button icons
#   - menu bar
#   - toolbar buttons
#   - menu item shortcut text
#   - sidebar filters panel label text
# dark
#   - divider line in sidebar filters panel
#   - bottom and right borders of toolbox buttons
# mid
#   - disabled tab bar scroll button icons
#   - border around focused text inputs in metadata editor tables
# highlight
#   - selected (focused or not) sidebar list and metadata editor table elements
# highlightedText
#   - selected (focused or not) sidebar list and metadata editor table elements
#   - divider between menu bar and toolbar
#   - top and left borders of toolbox buttons
# link
#   - hyperlinks in rich text
#
[active]
window = "#212121"
windowText = "#E0E0E0"
base = "#303030"
placeholderText = "#B3FFFFFF"
text = "#FFFFFF"
button = "#757575"
buttonText = "#FFFFFF"
dark = "#424242"
mid = "#595959"
highlight = "#264259"
highlightedText = "#FFFFFF"
link = "#2979FF"

[inactive]
window = "#212121"
windowText = "#E0E0E0"
base = "#303030"
placeholderText = "#B3FFFFFF"
text = "#FFFFFF"
button = "#757575"
buttonText = "#FFFFFF"
dark = "#424242"
mid = "#595959"
highlight = "#0078D7"
highlightedText = "#FFFFFF"
link = "#2979FF"

[disabled]
window = "#212121"
windowText = "#4DE0E0E0"
base = "#303030"
placeholderText = "#B3FFFFFF"
text = "#4DFFFFFF"
button = "#757575"
buttonText = "#4DFFFFFF"
dark = "#424242"
mid = "#595959"
highlight = "#0078D7"
highlightedText = "#4DFFFFFF"
link = "#2979FF"
